spring:
  datasource:
    ordersandpayments:
      url: jdbc:h2:mem:ordersandpayments;MODE=PostgreSQL
      username: root
      password: root
      driverClassName: org.h2.Driver
    notifications:
      url: jdbc:h2:mem:notifications;MODE=PostgreSQL
      username: root
      password: root
      driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect