spring:
  datasource:
    url: jdbc:h2:mem:spring_transactionality;MODE=PostgreSQL
    username: root
    password: root
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect