CREATE TABLE ORDERS
(
    ID                 VARCHAR(255)  NOT NULL,
    AMOUNT             DECIMAL(8, 6) NOT NULL,

    CONSTRAINT PK_ORDERS PRIMARY KEY (ID)
);

CREATE TABLE PAYMENTS
(
    ID                 VARCHAR(255)  NOT NULL,
    PAYMENT_METHOD     VARCHAR(255)  NOT NULL,

    CONSTRAINT PK_PAYMENTS PRIMARY KEY (ID)
);